// <auto-generated />
using System;
using JornadaMilhas.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JornadaMilhas.Migrations
{
    [DbContext(typeof(JornadaMilhasContext))]
    partial class JornadaMilhasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JornadaMilhasV1.Modelos.OfertaViagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<double>("Desconto")
                        .HasColumnType("float");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("RotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("OfertasViagem");
                });

            modelBuilder.Entity("JornadaMilhasV1.Modelos.Rota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("JornadaMilhasV1.Modelos.OfertaViagem", b =>
                {
                    b.HasOne("JornadaMilhasV1.Modelos.Rota", "Rota")
                        .WithMany("OfertasViagem")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JornadaMilhasV1.Modelos.Periodo", "Periodo", b1 =>
                        {
                            b1.Property<int>("OfertaViagemId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("DataFinal")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataFinal");

                            b1.Property<DateTime>("DataInicial")
                                .HasColumnType("datetime2")
                                .HasColumnName("DataInicial");

                            b1.HasKey("OfertaViagemId");

                            b1.ToTable("OfertasViagem");

                            b1.WithOwner()
                                .HasForeignKey("OfertaViagemId");
                        });

                    b.Navigation("Periodo")
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("JornadaMilhasV1.Modelos.Rota", b =>
                {
                    b.Navigation("OfertasViagem");
                });
#pragma warning restore 612, 618
        }
    }
}
